{% set name = "properties" %}
{% set version = "0.5.1" %}
{% set sha256 = "c8ad65e9f6596392fc4918f179248b0fae30e17dde2fa4667dfcccd064d827f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - numpy >=1.7
    - vectormath >=0.1.4

test:
  imports:
    - properties

about:
  home: http://github.com/aranzgeo/properties
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: documentation, validation, tab completion, serialization of properties

  description: |
    Properties provides structure to aid development in an interactive
    programming environment while allowing for an easy transition to
    production code. It emphasizes usability and reproducibility for
    developers and users at every stage of the code life cycle.
  doc_url: http://propertiespy.readthedocs.io/
  dev_url: https://github.com/aranzgeo/properties

extra:
  recipe-maintainers:
    - fwkoch
