travis:
  secure:
    BINSTAR_TOKEN: tEjLT1dWFprxvNXL+hE80qLtdqPuIqzA6nNRvp2m+ULIyAlHMqb/8Ajgzn2KzDv4z89/9c998Que0L9OOOVXaYRfNy3/R/TSmFvmWnQVidTSrwYF1vOPUwSRmZUt5AbhCtUAHYqwB6ihP7LKiFa5l1gB9Aiz+M1Wj3Dt7IJOFH2N2EV0R5pOEp0M1tsvxlNjKgjlVlq86Y6luufDOlQDKuGWJvd4Uyu0kii3gFEwT9qT3kBi6JV/CWb9d4wt4KdevKEeJv4VNht4W/YPeqL32zji0IlLsoIrTOuVj1sHMRKYauL9ZIpdtWEwsjDgUyf4Bn6bjiGe65wa99E8/fMWHYpohQX2aZIdrYJSUu6ukmrlJrDcTlNZMFN8iL90vCpVMGR9AZseN4biuoT5x1M+P6oYbLWss97j9+7II+khg5oeoYpWrj5Zg12as0WPI7ij6aDgJz/rdOIc0kDCk/aYHOHDXLI6Dpuk2rrs/RLQ4/zOvr0vn7H7jftjUy0YY8VfvjU65YC/CiFJAdAJAY/qgWvFG81gzO/hwm2ZBo6VGrKaSi8sa9PXjNQJSwaTAK9xGxrDcV8CryFzjNFZXZxrsSh4Qxyble3BEcj5nCNMMTiyDdBpVB9+p9aNJxKRz7WIoxDeJ1xN6qutoiitJfnxMrDGq9SF93QV8x2lD4P5vHs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
