travis:
  secure:
    BINSTAR_TOKEN: Pv0d0rFVenawwoKOMkorHk3OcrowDm9VlvfjfJYyWXSlSD/Mw9zyaCJaVmhGfuxK4OCr1meEnqQ1yKaM0hnFSjG57GsmXWjbHN7ii99NS0MsHU+7zI06u4P8swoTlG7baDNTGppyV8CsBLAMQUUZOAaUaw8OugGoEqB8ARS/YYjgWGdhY0By40zOtoxcnU4XmksSfNAXNwZBSyuU38FwUYlZMj+kpdiAapNn6JobyIVyT6FVvDzQFYmlb+MPTPoW+rxlZCowYyR+meKxSt4VU3sAFF/3Xy4mtH1xNVAiAOCt5BFQ4VlEafV9oWkS/DFvHh/heGkdhshNMW/wA9bA5y0jRXStw1RAw1oHfj7mFoMkBwZziqey0eQ1oCr+C7APg6hL+x1yjSLbniOPBWeSPeXVq1dauRcZyn78YcODgt0Bn7mZSDxFJgesgFjBLCRfATvOu7+mu3W3402wB6ZZIUi6Fc45DuHhiNlUsaWjBDd8VAlOaDnzPN1bia813zZTnHihzMiC2cvaws+cHncG4933TY0oukqifWpE3jSjWfjjV6VnO1+7cHQMhiFVru8PjA/0kEg7504uCqvqD0JaGWQ9CeV8wO6ZK7apg3d++sgedzdM5eyRBCdLs5eP+6HdVLUCWTT/85HM4tfx5PiQsoUli0XbVRO7Nb5kp4IcFw0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
